version: '3.8'

services:
  db:
    image: postgres:14.15-alpine3.21
    container_name: post-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dbpost
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
